name: setup

runs:
  using: composite

  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 10.0.0
    - uses: actions/setup-node@v4
      with:
        cache: "pnpm"
        node-version: 24
    - run: pnpm i
      shell: bash
