name: lint

on: pull_request

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm eslint . && pnpm prettier --check .
        shell: bash
