name: typecheck

on: pull_request

permissions:
  contents: read

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm typecheck
        shell: bash
